### ISSUE TITLE
Shared library paths are host OS dependent 

### ISSUE THREAD

**Issue by lucashecht** [unikraft/dynamic-apps#1]
I tried running various dynamic apps using the [`do.sh` script](https://github.com/unikraft-upb/scripts/blob/main/make-based/app-elfloader/do.sh) in qemu on my Arch system but get errors that the needed libraries cannot be located.

**Example**
running `./do.sh run bc` will yield the following failing syscalls:
```
access("/etc/ld.so.preload", R_OK) = No such file or directory (-2)
openat(AT_FDCWD, "/etc/ld.so.cache", O_RDONLY|O_CLOEXEC) = No such file or directory (-2)
openat(AT_FDCWD, "/usr/lib/glibc-hwcaps/x86-64-v2/libreadline.so.7", O_RDONLY|O_CLOEXEC) = No such file or directory (-2)
newfstatat(0xffffff9c, 0x47f92ee80, ...) = No such file or directory (-2)
openat(AT_FDCWD, "/usr/lib/libreadline.so.7", O_RDONLY|O_CLOEXEC) = No such file or directory (-2)
newfstatat(0xffffff9c, 0x47f92ee80, ...) = No such file or directory (-2)
/usr/bin/bc: error while loading shared libraries: libreadline.so.7: cannot open shared object file: No such file or directory
```

**Problem**
The loader uses the search paths of my Arch system to look for libs while the structure of the libs that are provided here and which is also mounted in qemu corresponds to what you would find in Ubuntu.

**Possible solution**
Provide the loader running in qemu with the correct search path to find the binaries provided in this repo.

**Comment by razvand** [comment]
Thanks, @lucashecht.

Hackathon points: 10
