### ISSUE TITLE
Add `vault` dynamic application build

### ISSUE THREAD

**Issue by StefanJum** [unikraft/dynamic-apps#24]
Add the [`vault` applications](https://www.vaultproject.io/) as a dynamic build.
Test it using [`app-elfloader`](https://github.com/unikraft/run-app-elfloader).
If any problems appear, open issues on the [Unikraft core repository](https://github.com/unikraft/unikraft/). 

The typical process of adding apps to the `dynamic-apps` repository is:

* Create the app directory that will store: the executable, depending shared libraries, configuration files, data files, etc.
* Use `apt download` to download the package(s) (`.deb`)
* Extract the executable, configuration and data files required to run the application.
* Update the configuration file, if required.
* Run the executable locally, to test it.
* Run the [`extract.sh`](https://github.com/unikraft/dynamic-apps/blob/master/extract.sh) script to collect the necessary shared libraries: 
* Now profit. Use [`app-elfloader`](https://github.com/unikraft/run-app-elfloader).

Hackathon points: 20

**Comment by StefanJum** [comment]
> Hello @StefanJum
> If this issue is not assigned to anyone yet, can I work on it?

All yours @chococandy63, go for it.

**Comment by chococandy63** [comment]
I set up `vault` on my fedora virtual machine by running the following commands:
`sudo dnf install -y dnf-plugins-core`
`sudo dnf config-manager --add-repo https://rpm.releases.hashicorp.com/fedora/hashicorp.repo`
`sudo dnf -y install vault`

Next, I created a directory `vault` inside `dynamic-apps` directory.  Inside `vault` directory, I ran this command `../extract.sh /usr/bin/vault` but it showed me this:

![image](https://github.com/unikraft/dynamic-apps/assets/79960426/06d54270-0c26-48f0-9c7e-703e83976e8b)

I tried running `ldd /usr/bin/vault` command to see the dynamic dependencies but it showed this:

![image](https://github.com/unikraft/dynamic-apps/assets/79960426/48f589e2-826b-4171-a9a8-251b805b8cc1)

@StefanJum Could you please tell me how do I move forward with this issue? I feel I am a beginner but would like to learn more about this process. 

Thanks!

**Comment by StefanJum** [comment]
@chococandy63 the argument passed to the `extract.sh` script should be a dynamic executable. Most likely the `/usr/bin/vault` file is a script, that ends up calling the actual ELF file. You will need to investigate the script and find out the location of the executable, and then pass that to the `extract.sh` script.

**Comment by chococandy63** [comment]
@StefanJum `/usr/bin/vault` is not a script as shown in the image below. It is a 64-bit ELF executable file. The `extract.sh` script is likely designed to work with dynamically linked executables, which have dependencies on shared libraries. However, since `/usr/bin/vault` is statically linked, it does not have any dynamic dependencies, which is why the ldd command does not show any output.

![image](https://github.com/unikraft/dynamic-apps/assets/79960426/916e1ea7-993c-4a2e-a57e-2786a0b2a38c)

What you think?

**Comment by StefanJum** [comment]
If `vault` is not a dynamic executable, then you can add it in the [`static-pie-apps`](https://github.com/unikraft/static-pie-apps/) repository. You can follow the examples of the applications that are already added there, and build a script that does the installation steps that you did on your machine.

**Comment by chococandy63** [comment]
Cool, I will get that done. Thanks for your guidance :)

**Comment by chococandy63** [comment]
@StefanJum Should I create an issue to remove issues related to the vault from the dynamic-apps repo?

**Comment by StefanJum** [comment]
> @StefanJum Should I create an issue to remove issues related to the vault from the dynamic-apps repo?

No need, I will close the issues sometime today.

**Comment by StefanJum** [comment]
Closed, as `vault` comes as a static pie elf.
